config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :maritime_terms

      root to: "users#index"
    end
  devise_for :users
  resources :maritime_terms
  root to: "maritime_terms#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/maritime_term.rb
class MaritimeTerm < ApplicationRecord
  validates :term, :explination, presence: true
  validates :term, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin
    before_action :authenticate_user!

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/maritime_terms_controller.rb
module Admin
  class MaritimeTermsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maritime_terms_controller.rb
class MaritimeTermsController < ApplicationController
  before_action :set_maritime_term, only: [:show, :edit, :update, :destroy]

  # GET /maritime_terms
  # GET /maritime_terms.json
  def index
    @maritime_terms = MaritimeTerm.order('term ASC')
  end

  # GET /maritime_terms/1
  # GET /maritime_terms/1.json
  def show
  end

  # GET /maritime_terms/new
  # def new
  #   @maritime_term = MaritimeTerm.new
  # end

  # GET /maritime_terms/1/edit
  # def edit
  # end

  # POST /maritime_terms
  # POST /maritime_terms.json
  # def create
  #   @maritime_term = MaritimeTerm.new(maritime_term_params)
  #
  #   respond_to do |format|
  #     if @maritime_term.save
  #       format.html { redirect_to @maritime_term, notice: 'Maritime term was successfully created.' }
  #       format.json { render :show, status: :created, location: @maritime_term }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @maritime_term.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /maritime_terms/1
  # PATCH/PUT /maritime_terms/1.json
  # def update
  #   respond_to do |format|
  #     if @maritime_term.update(maritime_term_params)
  #       format.html { redirect_to @maritime_term, notice: 'Maritime term was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @maritime_term }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @maritime_term.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /maritime_terms/1
  # DELETE /maritime_terms/1.json
  # def destroy
  #   @maritime_term.destroy
  #   respond_to do |format|
  #     format.html { redirect_to maritime_terms_url, notice: 'Maritime term was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maritime_term
      @maritime_term = MaritimeTerm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maritime_term_params
      params.require(:maritime_term).permit(:term, :explination)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maritime_terms_helper.rb
module MaritimeTermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarineLogisticsDictionary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body class="bg-gray-100">
      <script async src="https://cdn.contextcue.com/adsbycontextcue.js"></script>
      <%= render partial: 'shared/navigation' %>
      <div class="grid gap-4 p-8 sm:grid-cols-1 md:grid-cols-2">
        <div><%= yield %></div>
        <div>
          <ins class="adsbycontextcue" data-cc-site="00709622-a7c8-4388-bba8-a662bc746df3" data-cc-slot="d6BghddFm" style="style="width:300px;height:600px;"></ins>
        </div>
      </div>
      <ins class="adsbycontextcue" data-cc-site="00709622-a7c8-4388-bba8-a662bc746df3" data-cc-slot="d6BghddFm" style="display:block;"></ins>
    </body>
</html>


<div class="grid grid-rows-3 grid-flow-col gap-4">
  <div class="row-span-3 ..."></div>
  <div class="row-span-1 col-span-2 ..."></div>
  <div class="row-span-2 col-span-2 ..."></div>
</div>

app/views/maritime_terms/index.html.erb
<br><br>
<div class="max-w mb-4 rounded overflow-hidden shadow-lg bg-white">
  <div class="px-6 py-4">
    <p class="text-gray-700 text-base">
      In an effort to simplify the maritime and marine logistics community, we are assembling a database of maritime and marine logistics terms free of use for you.
    </p>
    <p class="text-gray-700 text-base pt-2">Please be patient with us as we build this app out fully. In the coming months we will be adding search and a refined user interface.</p>
  </div>
</div>

<div class="max-w mb-4 rounded overflow-hidden content-center bg-white">
<table class="table-auto p-8">
  <thead>
    <tr>
      <th class="px-4 py-2">Term</th>
      <th class="px-4 py-2">Explanation</th>
      <th class="px-4 py-2">Link</th>
    </tr>
  </thead>
  <tbody>
    <% @maritime_terms.each do |maritime_term| %>
      <tr>
        <td class="border px-4 py-2"><%= link_to maritime_term.term, maritime_term%></td>
        <td class="border px-4 py-2"><%= maritime_term.explination.truncate(30)  %></td>
        <td class="border px-4 py-2"><%= link_to 'Show', maritime_term%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="max-w mb-4 rounded overflow-hidden bg-white">
<p class="text-gray-700 text-base px-6 py-4 ">Have a suggenstion or want to contrubute? Send us an email to nick at boxwhere.com</p>

<p class='text-gray-700 px-6 py-4'>All definitions here are without warranty.</p>
</div>

app/views/maritime_terms/show.html.erb
<div class="max-w rounded overflow-hidden bg-white shadow-lg">
  <div class="px-10 py-8">
    <div class="font-bold text-xl mb-2"><%= @maritime_term.term %></div>
    <p class="text-gray-700 text-base">
      <%= @maritime_term.explination %>
    </p>
  </div>
  <div class="p-8">
    <%= link_to 'Back', maritime_terms_path, class: 'bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded' %>
  </div>

</div>

app/views/shared/_navigation.html.erb
<nav class="flex items-center justify-between flex-wrap bg-blue-400 p-6">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <span class="font-semibold text-xl tracking-tight">Maritime &amp; Marine Logistics Terms</span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <%= link_to "Home", root_path, class: 'block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4' %>
    </div>
    <div>
      <a href="https://www.boxwhere.com" class="inline-block text-sm px-4 py-2 leading-none border rounded text-white visited:text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Back to BoxWhere</a>
    </div>
  </div>
</nav>